server:
  port: 8081

spring:
  application:
    name: book-service
  data:
    mongodb:
      uri: mongodb://root:All4one7!@192.168.1.83:27017/book_catalog?authSource=admin

logging:
  config: classpath:logback-spring.xml
  level:
    root: INFO

