server:
  port: 8082

spring:
  application:
    name: user-service
  data:
    mongodb:
      uri: mongodb://root:password@192.168.1.83:27018/book_users?authSource=admin

logging:
  config: classpath:logback-spring.xml
  level:
    root: INFO, DEBUG, ERROR

